import { useState } from 'react'

type Member = { id: string; name: string; role: string; color: string }
type Agent = { id: string; name: string; specialty: string; state: string; color: string }
type Message = { id: string; author: string; body: string; kind: 'human' | 'agent' | 'file'; createdAt: number }
type Task = { id: string; title: string; status: 'backlog' | 'working' | 'review' | 'complete'; assignee: string; output?: string; criteria?: string; priority?: string; deadline?: string; roles?: Partial<Record<'owner' | 'researcher' | 'analyst' | 'reviewer', string>>; messages?: Message[]; mode?: 'research' | 'coding' | 'writing' | 'planning'; subtasks?: string[]; suggestedAgents?: string[]; suggestedTools?: string[]; risks?: string[]; plan?: Array<{ id: string; title: string; owner: string; status: 'pending' | 'active' | 'done' }>; autopilot?: boolean }
type Artifact = { id: string; taskId: string; title: string; content: string; createdAt: number; agentId: string }
type Room = { id: string; name: string; floor: string; adminId: string; members: Member[]; statuses: Record<string, string>; agents: Agent[]; tasks: Task[]; events: string[]; artifacts?: Artifact[]; executionRuns?: Array<{ id: string; taskId?: string; agentId: string; status: string; model: string; usage?: { totalTokens?: number }; error?: string }> }
type Account = { id: string; name: string; role: string; color: string }
type Store = { accounts: Account[]; rooms: Room[] }

type Props = { task: Task; room: Room; current: Account; data: any; setData: (data: any) => void; onBack: () => void; onStatus: () => void; onAskAgent: (instruction: string) => void; flash: (message: string) => void }
const uid = () => Math.random().toString(36).slice(2, 9)

export default function TaskRoom({ task, room, current, data, setData, onBack, onStatus, onAskAgent, flash }: Props) {
  const [ask, setAsk] = useState('')
  const [message, setMessage] = useState('')
  const [replaying, setReplaying] = useState(false)
  const [improveMenu, setImproveMenu] = useState<string | null>(null)
  const [briefMode, setBriefMode] = useState<'brief' | 'catchup' | null>(null)
  const [autopilot, setAutopilot] = useState(Boolean(task.autopilot))
  const [roleAssignees, setRoleAssignees] = useState(task.roles || {})
  const [deadline, setDeadline] = useState(task.deadline || '')
  const statusLabel = task.status === 'backlog' ? 'Started' : task.status === 'working' ? 'In progress' : task.status === 'review' ? 'In review' : 'Completed'
  const agentOwner = room.agents.find(agent => agent.id === task.assignee)
  const humanOwner = room.members.find(member => member.id === task.assignee)
  const run = [...(room.executionRuns || [])].reverse().find(item => item.taskId === task.id)
  const modeLabel = task.mode === 'coding' ? 'CODING WORKSPACE' : task.mode === 'writing' ? 'WRITING WORKSPACE' : task.mode === 'planning' ? 'PLANNING WORKSPACE' : 'RESEARCH WORKSPACE'
  const defaultPlan = [{ id: '1', title: task.mode === 'coding' ? 'Inspect the implementation' : task.mode === 'planning' ? 'Understand the outcome' : 'Gather authorized context', owner: 'Planner', status: 'done' as const }, { id: '2', title: task.mode === 'coding' ? 'Identify the safest change' : task.mode === 'writing' ? 'Draft the first version' : 'Analyze the strongest evidence', owner: agentOwner?.name || 'Researcher', status: task.status === 'backlog' ? 'pending' as const : 'active' as const }, { id: '3', title: 'Challenge assumptions and review', owner: 'Reviewer', status: task.status === 'review' || task.status === 'complete' ? 'active' as const : 'pending' as const }, { id: '4', title: 'Human approval', owner: 'You', status: task.status === 'complete' ? 'done' as const : 'pending' as const }]
  const plan = task.plan?.length ? task.plan : defaultPlan
  const taskArtifacts = (room.artifacts || []).filter(artifact => artifact.taskId === task.id)
  const workingAgents = room.agents.filter(agent => agent.state === 'working')
  const isAdmin = current.id === room.adminId
  const people = [...room.members.map(member => ({ id: member.id, label: `${member.name} · human` })), ...room.agents.map(agent => ({ id: agent.id, label: `${agent.name} · ${agent.specialty}` }))]
  const saveStaffing = () => { updateTask({ ...task, roles: roleAssignees, deadline }, `${current.name} updated task staffing and timeline`); flash('Task staffing saved') }
  const updateTask = (next: Task, event: string) => setData({ ...data, rooms: data.rooms.map((item: Room) => item.id === room.id ? { ...item, tasks: item.tasks.map((existing: Task) => existing.id === task.id ? next : existing), events: [...item.events, event] } : item) })
  const addMessage = (body: string, kind: Message['kind'] = 'human') => updateTask({ ...task, messages: [...(task.messages || []), { id: uid(), author: current.name, body, kind, createdAt: Date.now() }] }, `${current.name} added context to “${task.title}”`)
  const submitAsk = (event: React.FormEvent) => { event.preventDefault(); if (!ask.trim()) return; const instruction = ask.trim(); addMessage(instruction); setAsk(''); onAskAgent(instruction) }
  const submitMessage = (event: React.FormEvent) => { event.preventDefault(); if (!message.trim()) return; addMessage(message.trim()); setMessage(''); flash('Message added to the task') }
  const attachFile = () => { const input = document.createElement('input'); input.type = 'file'; input.onchange = () => { const file = input.files?.[0]; if (file) { addMessage(file.name, 'file'); flash(`${file.name} added to task context`) } }; input.click() }
  const runImprovement = (instruction: string) => { setImproveMenu(null); onAskAgent(`Improve the latest artifact. ${instruction}. Preserve the previous version and explain what changed.`) }
  const runChallenge = () => onAskAgent('Challenge the latest artifact. Find contradictions, missing evidence, weak assumptions, errors, and alternative interpretations. Return a structured critique.')
  const graph = [{ label: 'YOU', state: 'done' }, { label: 'PLANNER', state: task.status === 'backlog' ? 'idle' : 'done' }, { label: agentOwner?.name || 'RESEARCH', state: run?.status === 'FAILED' ? 'error' : workingAgents.length ? 'active' : task.output ? 'done' : 'idle' }, { label: 'REVIEWER', state: task.status === 'review' ? 'active' : task.status === 'complete' ? 'done' : 'idle' }, { label: taskArtifacts.length ? 'FINAL ARTIFACT' : 'ARTIFACT', state: task.status === 'complete' ? 'done' : taskArtifacts.length ? 'active' : 'idle' }]
  return <main className="task-room">
    <header className="task-room-header"><button className="back" onClick={onBack}>← Workspace</button><div className="task-room-heading"><strong>{task.title}</strong><span><i className="status-dot" /> {room.members.length} humans · AI agents currently unavailable</span></div><div className="task-header-actions"><button className="quiet-button" onClick={() => setBriefMode('brief')}>Brief me</button><button className="quiet-button" onClick={() => setBriefMode('catchup')}>Catch me up</button><button className="autopilot-toggle unavailable-control" disabled title="AI agents are temporarily unavailable">AI unavailable</button><button className="quiet-button">•••</button></div></header>
    <section className="ask-bar unavailable-bar"><span className="ask-mark">✦</span><div><strong>Ask SELTERN</strong><p>AI task execution is currently unavailable.</p></div><span className="unavailable-badge">CURRENTLY UNAVAILABLE</span></section>
    <div className="task-room-grid">
      <article className="task-thread">
        <div className="task-room-summary"><div><span className="eyebrow">{modeLabel}</span><h1>{task.title}</h1><p>{task.criteria || 'A useful result is produced, checked, and reviewed by the team.'}</p><div className="why-line">Why this setup: {task.suggestedAgents?.length ? `${task.suggestedAgents.join(', ')} selected from the task requirements.` : 'SELTERN will choose agents from the task requirements.'}</div></div><div className="task-room-actions"><button className={`status-pill ${task.status}`} onClick={onStatus}>{statusLabel}</button><button onClick={() => setReplaying(!replaying)}>{replaying ? '■ Stop replay' : '▶ Replay work'}</button></div></div>
        {replaying && <div className="replay-strip"><span className="replay-dot" /> Reconstructing the collaboration: human context → agents → review → artifact</div>}{briefMode && <div className="brief-card"><div><span className="eyebrow">{briefMode === 'brief' ? 'BRIEF ME' : 'CATCH ME UP'}</span><button onClick={() => setBriefMode(null)}>×</button></div><p>{briefMode === 'brief' ? `You joined this task recently. ${agentOwner?.name || 'The assigned agent'} is responsible for the current work. ${task.output ? 'An output is ready for review.' : 'The team is still gathering context.'} Current status: ${statusLabel}.` : `What happened: the task was created and scoped. What matters: ${task.criteria || task.title}. What changed: ${room.events.slice(-2).join(' · ') || 'Nothing yet'}. Next: review the current plan and choose an owner.`}</p></div>}
        <section className="execution-graph"><div className="section-label">LIVE EXECUTION GRAPH <span>{run ? run.status : 'WAITING'}</span></div><div className="graph-flow">{graph.map((node, index) => <div className="graph-step" key={node.label}><div className={`graph-node ${node.state}`}><i />{node.label}</div>{index < graph.length - 1 && <div className={`graph-link ${node.state === 'active' ? 'active' : ''}`} />}</div>)}</div></section>
        <div className="plan-panel"><div className="thread-label"><span>SELTERN PLAN</span><small>Living execution plan · {autopilot ? 'autopilot on' : 'human controlled'}</small></div>{plan.map(step => <div className={`plan-step ${step.status}`} key={step.id}><i /> <b>{step.title}</b><span>{step.owner}</span></div>)}</div><div className="thread-label"><span>THREAD</span><small>Humans + agents</small></div>
        <div className="thread-list">{(task.messages || []).map(item => <div className={`thread-message ${item.kind}`} key={item.id}><div className="thread-avatar" style={{ background: item.kind === 'agent' ? '#91b8ad' : current.color }}>{item.kind === 'agent' ? 'AI' : item.author.slice(0, 2).toUpperCase()}</div><div><strong>{item.author}</strong><small>{item.kind === 'agent' ? 'agent update' : 'human collaborator'}</small>{item.kind === 'file' ? <div className="thread-file">📄 {item.body}</div> : <p>{item.body}</p>}</div></div>)}{task.output && <div className="thread-message agent"><div className="thread-avatar" style={{ background: '#91b8ad' }}>AI</div><div><strong>{agentOwner?.name || 'AI coworker'}</strong><small>execution result</small><p>{task.output}</p></div></div>}{!(task.messages || []).length && !task.output && <div className="thread-empty">Ask SELTERN for the first move, or add the context your team needs.</div>}</div>
        <div className="thread-toolbar"><button onClick={attachFile}>+ Add file</button><button onClick={() => setMessage('@ ')}>@ Mention</button><button className="unavailable-control" disabled title="AI agents are temporarily unavailable">AI unavailable</button><button className="unavailable-control" disabled title="AI agents are temporarily unavailable">Challenge unavailable</button><button onClick={onStatus}>{task.status === 'review' ? 'Approve' : 'Review'}</button></div>
        <form className="thread-composer" onSubmit={submitMessage}><input value={message} onChange={event => setMessage(event.target.value)} placeholder="Write a message…" /><button className="enter-button">Send</button></form>
      </article>
      <aside className="task-room-side">
        <section className="room-panel memory-panel"><div className="panel-heading"><span>SELTERN REMEMBERS</span><button>edit</button></div><div className="risk-radar">{(task.risks || ['No active risks detected']).map((risk, index) => <span key={`${risk}-${index}`} className={risk === 'No active risks detected' ? 'safe' : ''}>{risk === 'No active risks detected' ? '✓' : '⚠'} {risk}</span>)}</div><div className="memory-item"><b>Objective</b><span>{task.title}</span></div><div className="memory-item"><b>Constraints</b><span>{task.criteria || 'No additional constraints yet.'}</span></div><div className="memory-item"><b>Decisions</b><span>{room.events.filter(event => event.toLowerCase().includes('constraint') || event.toLowerCase().includes('decision')).slice(-1)[0] || 'No decisions recorded.'}</span></div><div className="memory-item"><b>Open questions</b><span>What should the team validate before approval?</span></div></section>
        <section className="room-panel staffing-panel"><div className="panel-heading"><span>STAFFING & TIMELINE</span><small>{isAdmin ? 'ADMIN' : 'VIEW ONLY'}</small></div>{isAdmin ? <><label>Owner<select value={roleAssignees.owner || task.assignee} onChange={event => setRoleAssignees({ ...roleAssignees, owner: event.target.value })}><option value="">Unassigned</option>{people.map(person => <option value={person.id} key={`owner-${person.id}`}>{person.label}</option>)}</select></label><label>Researcher<select value={roleAssignees.researcher || ''} onChange={event => setRoleAssignees({ ...roleAssignees, researcher: event.target.value })}><option value="">Not assigned</option>{people.map(person => <option value={person.id} key={`research-${person.id}`}>{person.label}</option>)}</select></label><label>Analyst<select value={roleAssignees.analyst || ''} onChange={event => setRoleAssignees({ ...roleAssignees, analyst: event.target.value })}><option value="">Not assigned</option>{people.map(person => <option value={person.id} key={`analyst-${person.id}`}>{person.label}</option>)}</select></label><label>Reviewer<select value={roleAssignees.reviewer || ''} onChange={event => setRoleAssignees({ ...roleAssignees, reviewer: event.target.value })}><option value="">Not assigned</option>{people.map(person => <option value={person.id} key={`review-${person.id}`}>{person.label}</option>)}</select></label><label>Deadline<input type="datetime-local" value={deadline} onChange={event => setDeadline(event.target.value)} /></label><button className="save-staffing" onClick={saveStaffing}>Save staffing</button></> : <p className="panel-empty">The room admin controls task roles and deadlines.</p>}</section><section className="room-panel"><div className="panel-heading"><span>AGENTS</span><small>UNAVAILABLE</small></div><div className="unavailable-panel compact"><span className="eyebrow">CURRENTLY UNAVAILABLE</span><p>AI agents and OpenRouter execution are temporarily unavailable. Human teammates can continue the task and update its status.</p></div></section>
        <section className="room-panel"><div className="panel-heading"><span>CONTEXT</span><button onClick={attachFile}>+ add</button></div><div className="context-row">📄 <span>Files added to this task</span><b>{(task.messages || []).filter(item => item.kind === 'file').length}</b></div><div className="context-row">⌁ <span>Room activity</span><b>{room.events.length}</b></div><div className="context-row">◈ <span>Authorized tools</span><b>2</b></div></section>
        <section className="room-panel artifacts-panel"><div className="panel-heading"><span>ARTIFACTS</span><small>{taskArtifacts.length}</small></div>{taskArtifacts.length ? taskArtifacts.map(artifact => <div className="artifact-row" key={artifact.id}><div><span>DOCUMENT</span><strong>{artifact.title}</strong><small>{artifact.content.slice(0, 90)}…</small></div><div className="artifact-actions"><button className="unavailable-control" disabled title="AI agents are temporarily unavailable">Improve unavailable</button><button className="unavailable-control" disabled title="AI agents are temporarily unavailable">Co-work unavailable</button><button className="unavailable-control" disabled title="AI agents are temporarily unavailable">Challenge unavailable</button></div>{improveMenu === artifact.id && <div />}</div>) : <p className="panel-empty">Your first meaningful result will become an artifact here.</p>}</section>
        <section className="room-panel approval-panel"><div className="panel-heading"><span>REVIEW</span><small>{task.status === 'review' ? 'ACTION NEEDED' : 'TRACKED'}</small></div>{task.status === 'review' ? <><p>Review the artifact before this task becomes complete.</p><div className="approval-actions"><button className="enter-button" onClick={onStatus}>Approve</button><button className="unavailable-control" disabled title="AI agents are temporarily unavailable">Challenge unavailable</button></div></> : <p>{task.status === 'complete' ? 'Approved and complete.' : 'Human approval will be requested when the output is ready.'}</p>}</section>
      </aside>
    </div>
    <section className="task-timeline"><div className="timeline-heading"><span className="eyebrow">TASK TIMELINE</span><small>Every meaningful change</small></div>{room.events.slice(-10).reverse().map((event, index) => <div className="timeline-event" key={`${event}-${index}`}><i /><time>{index + 1}m ago</time><span>{event}</span></div>)}</section>
  </main>
}
