import { useEffect, useState } from 'react'

type Props = { room: any; current: any; onClose: () => void; onTask: (id: string) => void; onAgent: (id: string) => void; onAddAgent: () => void }
const taskState = (task: any) => task.status === 'backlog' ? 'READY' : task.status === 'working' ? 'WORKING' : task.status === 'review' ? 'REVIEWING' : 'COMPLETE'
const stateClass = (task: any) => task.status === 'backlog' ? 'ready' : task.status === 'working' ? 'working' : task.status === 'review' ? 'reviewing' : 'complete'
export default function SpatialFloor({ room, current, onClose, onTask, onAgent, onAddAgent }: Props) {
  const [selectedTask, setSelectedTask] = useState<any>(room.tasks[0])
  const [selectedAgent, setSelectedAgent] = useState<any>(null)
  const [following, setFollowing] = useState<string | null>(null)
  const [warRoom, setWarRoom] = useState(false)
  const [spaceHint, setSpaceHint] = useState(true)
  useEffect(() => { const handler = (event: KeyboardEvent) => { if (event.key === 'Escape' || event.code === 'Space') { event.preventDefault(); onClose() } }; addEventListener('keydown', handler); return () => removeEventListener('keydown', handler) }, [onClose])
  useEffect(() => { if (following) { const agent = room.agents.find((item: any) => item.id === following); setSelectedAgent(agent) } }, [following, room.agents])
  const focusTask = (task: any) => { setSelectedTask(task); setSelectedAgent(null); setSpaceHint(false) }
  return <main className={`floor-view ${warRoom ? 'war-room' : ''}`}>
    <header className="floor-header"><button className="floor-back" onClick={onClose}>← Exit Floor</button><div><span className="eyebrow">SHARED WORKPLACE / FLOOR</span><strong>{room.name}</strong></div><div className="floor-controls"><span><i className="pulse-dot" /> {room.tasks.filter((task: any) => task.status === 'working').length} active work</span><button className={warRoom ? 'active' : ''} onClick={() => setWarRoom(!warRoom)}>◈ {warRoom ? 'Exit war room' : 'War room'}</button><button onClick={() => { setFollowing(null); setSelectedTask(undefined); setSelectedAgent(null) }}>Reset view</button></div></header>
    <section className="floor-stage"><div className="floor-ambient" /><div className="floor-grid" /><div className="floor-spine" />
      {room.members.map((person: any, index: number) => <button className={`floor-human human-${(index % 4) + 1}`} key={person.id} onClick={() => setSpaceHint(false)}><span className="human-avatar" style={{ background: person.color }}>{person.name.slice(0, 2).toUpperCase()}</span><strong>{person.name}</strong><small>{room.statuses[person.id] || 'away'}</small><i /></button>)}
      {room.agents.map((agent: any, index: number) => <button className={`floor-agent agent-${(index % 4) + 1} ${agent.state}`} key={agent.id} onClick={() => { setSelectedAgent(agent); onAgent(agent.id); setSpaceHint(false) }}><span className="agent-orbit"><b /><i /><em /></span><strong>{agent.name}</strong><small>{agent.state === 'working' ? 'working now' : agent.specialty}</small><label>{agent.state === 'working' ? '● ACTIVE' : '○ WAITING'}</label></button>)}
      {room.tasks.map((task: any, index: number) => <button className={`work-object work-${(index % 5) + 1} ${stateClass(task)} ${selectedTask?.id === task.id ? 'selected' : ''}`} key={task.id} onClick={() => focusTask(task)}><span className="object-halo" /><span className="object-core">{task.status === 'complete' ? '✓' : task.status === 'review' ? '!' : '◇'}</span><strong>{task.title}</strong><small>{taskState(task)} · {task.assignee ? 'assigned' : 'unassigned'}</small><i className="object-pulse" /></button>)}
      {room.tasks.map((task: any, index: number) => <div className={`work-edge edge-${(index % 5) + 1}`} key={`edge-${task.id}`} />)}
      {warRoom && <div className="war-core"><span>DECISION SPACE</span><strong>{selectedTask?.title || 'Choose a task'}</strong><small>Evidence · disagreement · human judgment</small><div><button onClick={() => selectedTask && onTask(selectedTask.id)}>Enter task room</button><button onClick={() => setWarRoom(false)}>Return to floor</button></div></div>}
      {spaceHint && <div className="floor-intro"><span className="eyebrow">THE FLOOR</span><h1>The workplace<br/><em>is alive.</em></h1><p>Click active work to enter it. Click an agent to inspect their work. Press Space anytime to leave.</p><button onClick={() => setSpaceHint(false)}>Explore the floor ↗</button></div>}
    </section>
    <aside className="floor-inspector">{selectedAgent ? <><span className="eyebrow">AGENT INSPECTOR</span><h2>{selectedAgent.name}</h2><p className="agent-mood">“{selectedAgent.state === 'working' ? 'I’m investigating the evidence.' : 'I’m waiting for the next assignment.'}”</p><div className="inspector-stat"><span>Specialty</span><b>{selectedAgent.specialty}</b></div><div className="inspector-stat"><span>State</span><b>{selectedAgent.state}</b></div><div className="inspector-stat"><span>Current work</span><b>{room.tasks.find((task: any) => task.assignee === selectedAgent.id)?.title || 'No assigned task'}</b></div><button className="follow-button" onClick={() => setFollowing(following === selectedAgent.id ? null : selectedAgent.id)}>{following === selectedAgent.id ? 'Following agent' : 'Follow this agent'} ↗</button><button className="join-button" onClick={() => { const task = room.tasks.find((item: any) => item.assignee === selectedAgent.id); if (task) onTask(task.id) }}>Join their work</button></> : selectedTask ? <><span className="eyebrow">ACTIVE WORK</span><h2>{selectedTask.title}</h2><div className={`inspector-state ${stateClass(selectedTask)}`}>{taskState(selectedTask)}</div><p>{selectedTask.criteria || 'This work has no completion criteria yet.'}</p><div className="inspector-stat"><span>People in the work</span><b>{room.members.length} humans · {room.agents.length} agents</b></div><div className="inspector-stat"><span>Plan</span><b>{selectedTask.plan?.length || 4} steps · {selectedTask.suggestedAgents?.join(' · ') || 'team forming'}</b></div><div className="inspector-actions"><button className="join-button" onClick={() => onTask(selectedTask.id)}>Enter task room ↗</button><button onClick={() => setWarRoom(true)}>Open war room</button></div></> : <><span className="eyebrow">WORKPLACE</span><h2>{room.name}</h2><p>Select a living work object or agent to inspect the current state.</p><button className="join-button unavailable-control" disabled title="AI agents are temporarily unavailable">AI agents currently unavailable</button></>}</aside><footer className="floor-footer"><span><i className="pulse-dot" /> Shared state / synced</span><span>{following ? `Following ${selectedAgent?.name || 'agent'}` : 'SPACE / exit floor'} · {current.name} is here</span></footer></main>
}
